### ISSUE TITLE
External library support broken

### ISSUE THREAD

**Issue by justbennet** [OSC/bc_osc_jupyter#29]
Not sure whether this is is being maintained by anyone now, but the template scripts use `module` to purge the module environment.

For user who are using a Python library that requires other modules be loaded so the libraries are accessible to Python, e.g., `gdal`, this breaks under the scheme presented here and would require that the installers of the Jupyter app also load all modules that might be needed by users.

Is there a reason not to use the environment that the user sets up with, for example, Lmod's default collection device?  I am wondering if there was some specific reason for totally purging
all modules prior to Jupyter's start.

**Comment by MorganRodgers** [comment]
Hi @justbennet. This project is indeed maintained; it is in production at Ohio Supercomputer Center and is updated when we need. Purging the module environment was a deliberate choice we made to ensure that the environment starts off working. Other sites may have implemented their Jupyter Batch Connect applications differently.

For OnDemand 2.0 the OnDemand team intends to improve Batch Connect and better supporting module systems is certainly a consideration for that work. For the time being there are a few solutions for loading custom environments. 

One solution adds a Softwares(sic) tab to Jupyter Notebook ([jupyter-lmod](https://github.com/cmd-ntrf/jupyter-lmod)) which should work for all kernels including the non-Python kernels. When we tested `jupyter-lmod` we found that OSC-provided kernels overwrote the module environment that the extension set, which isn't ideal. Another issue with this method is that it does not support the command `module use`, so user-defined modules cannot be accessed. Due to a perceived lack of interest from the OSC community we have decided not to dedicate dev time to those issues at this time. If you are an admin at another site, or have been granted developer access to your OnDemand installation, you can alter your Jupyter app as was done in this example: https://github.com/OSC/bc_example_jupyter/pull/8/files.

Another option provides a line magic command which is specific to iPython kernels (https://github.com/PSC-PublicHealth/pha-nbextensions). When I tested this extension I was able to use it without having to update the Batch Connect application. An example workbook where they use the command is available here: https://github.com/PSC-PublicHealth/pha-nbextensions/blob/master/doc/WorkingExample_update_environment.ipynb. This one is nice because it works when installed using `pip install --user`, unfortunately for OSC where we also provide the Julia kernel there is no support for non-Python languages.

A final option, which won't work in every case, is using a Conda environment to provide your iPython kernel. Directions for how to do this are available here: https://www.osc.edu/resources/getting_started/howto/howto_use_a_conda_environment_with_jupyter.

**Comment by justbennet** [comment]
Thanks a ton for this quick reply!

I will try the update_environment extension, as that looks like it might work best for us here.

Glad to see this is being maintained.  I am at Dante's old school, and I know he went off to fame and fortune on the west coast.  :-)
